Transitioned from using balldontlie api to nba_api.  nba_api has an associated Python library to use for calling the api.

In [1]:
!pip install nba_api

Collecting nba_api
  Downloading nba_api-1.10.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from nba_api) (1.26.4)
Requirement already satisfied: pandas>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from nba_api) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /opt/anaconda3/lib/python3.12/site-packages (from nba_api) (2.32.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=2.2.0->nba_api) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=2.2.0->nba_api) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2025.7.14)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.16.0)
Downloading nba_api-1.10.0-py3-none-any.whl (285 kB)
Installing collected packages: nba_api
Successfully installed nba_api-1.10.0

In [62]:
import pandas as pd
import numpy as np
from nba_api.stats.endpoints import leaguedashplayerstats

In [63]:
#get league and player stats for the 2024-25 NBA season via the nba_api library and convert to dataframe
player_stats = leaguedashplayerstats.LeagueDashPlayerStats(season = '2024-25').get_data_frames()[0]
player_stats.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK
0,1630639,A.J. Lawson,A.J.,1610612761,TOR,24.0,26,14,12,0.538,486.410000,80,190,0.421,33,101,0.327,43,63,0.683,20,66,86,31,15,13,6,12,44,38,236,-17,427.7,2,0,424.0,424,364,146,239,379,352,340,388,282,281,319,281,267,419,364,359,368,397,414,397,383,241,200,327,337,299,375,159,44,364
1,1631260,AJ Green,AJ,1610612749,MIL,25.0,73,44,29,0.603,1659.141667,182,424,0.429,155,363,0.427,22,27,0.815,18,156,174,108,40,37,7,3,157,50,541,227,1003.8,0,0,1066.0,86,62,362,164,152,231,220,353,58,77,37,364,372,180,381,227,261,215,286,235,370,99,498,290,214,62,247,281,44,225
2,1642358,AJ Johnson,AJ,1610612764,WAS,20.0,29,8,21,0.276,638.386667,82,213,0.385,24,90,0.267,32,37,0.865,8,51,59,76,35,12,3,18,50,27,220,-152,414.8,0,0,409.0,412,445,253,473,338,348,325,472,319,294,425,312,335,87,455,386,410,281,313,406,441,312,217,369,347,495,379,281,44,372
3,203932,Aaron Gordon,Aaron,1610612743,DEN,29.0,51,33,18,0.647,1446.716667,264,497,0.531,75,172,0.436,145,179,0.810,80,167,247,164,73,23,14,37,82,137,748,301,1328.4,3,0,1308.0,275,166,211,101,185,150,182,79,191,222,24,89,93,196,104,206,173,128,180,329,265,451,301,107,139,41,183,134,44,181
4,1628988,Aaron Holiday,Aaron,1610612745,HOU,28.0,62,39,23,0.629,792.246667,117,268,0.437,72,181,0.398,34,41,0.829,13,65,78,83,37,19,11,11,64,49,340,88,611.1,0,0,633.0,192,100,283,124,305,304,297,325,197,216,91,300,321,142,419,361,377,259,303,353,311,224,259,292,292,115,322,281,44,315

In [64]:
#identify column headers
print(f"Column Headers:")
print("-"*25)
player_stats.columns.tolist()

Column Headers:
-------------------------

['PLAYER_ID',
 'PLAYER_NAME',
 'NICKNAME',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'AGE',
 'GP',
 'W',
 'L',
 'W_PCT',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'TOV',
 'STL',
 'BLK',
 'BLKA',
 'PF',
 'PFD',
 'PTS',
 'PLUS_MINUS',
 'NBA_FANTASY_PTS',
 'DD2',
 'TD3',
 'WNBA_FANTASY_PTS',
 'GP_RANK',
 'W_RANK',
 'L_RANK',
 'W_PCT_RANK',
 'MIN_RANK',
 'FGM_RANK',
 'FGA_RANK',
 'FG_PCT_RANK',
 'FG3M_RANK',
 'FG3A_RANK',
 'FG3_PCT_RANK',
 'FTM_RANK',
 'FTA_RANK',
 'FT_PCT_RANK',
 'OREB_RANK',
 'DREB_RANK',
 'REB_RANK',
 'AST_RANK',
 'TOV_RANK',
 'STL_RANK',
 'BLK_RANK',
 'BLKA_RANK',
 'PF_RANK',
 'PFD_RANK',
 'PTS_RANK',
 'PLUS_MINUS_RANK',
 'NBA_FANTASY_PTS_RANK',
 'DD2_RANK',
 'TD3_RANK',
 'WNBA_FANTASY_PTS_RANK']

# Transformation 1: Standardize Player Names

## Create a new column that shows player name cleaned up to all lower letters and remove any punctuation

In [65]:
player_stats['Player_clean'] = player_stats['PLAYER_NAME'].str.lower().str.strip().replace(',', '').str.replace('.', '')
player_stats.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,Player_clean
0,1630639,A.J. Lawson,A.J.,1610612761,TOR,24.0,26,14,12,0.538,486.410000,80,190,0.421,33,101,0.327,43,63,0.683,20,66,86,31,15,13,6,12,44,38,236,-17,427.7,2,0,424.0,424,364,146,239,379,352,340,388,282,281,319,281,267,419,364,359,368,397,414,397,383,241,200,327,337,299,375,159,44,364,aj lawson
1,1631260,AJ Green,AJ,1610612749,MIL,25.0,73,44,29,0.603,1659.141667,182,424,0.429,155,363,0.427,22,27,0.815,18,156,174,108,40,37,7,3,157,50,541,227,1003.8,0,0,1066.0,86,62,362,164,152,231,220,353,58,77,37,364,372,180,381,227,261,215,286,235,370,99,498,290,214,62,247,281,44,225,aj green
2,1642358,AJ Johnson,AJ,1610612764,WAS,20.0,29,8,21,0.276,638.386667,82,213,0.385,24,90,0.267,32,37,0.865,8,51,59,76,35,12,3,18,50,27,220,-152,414.8,0,0,409.0,412,445,253,473,338,348,325,472,319,294,425,312,335,87,455,386,410,281,313,406,441,312,217,369,347,495,379,281,44,372,aj johnson
3,203932,Aaron Gordon,Aaron,1610612743,DEN,29.0,51,33,18,0.647,1446.716667,264,497,0.531,75,172,0.436,145,179,0.810,80,167,247,164,73,23,14,37,82,137,748,301,1328.4,3,0,1308.0,275,166,211,101,185,150,182,79,191,222,24,89,93,196,104,206,173,128,180,329,265,451,301,107,139,41,183,134,44,181,aaron gordon
4,1628988,Aaron Holiday,Aaron,1610612745,HOU,28.0,62,39,23,0.629,792.246667,117,268,0.437,72,181,0.398,34,41,0.829,13,65,78,83,37,19,11,11,64,49,340,88,611.1,0,0,633.0,192,100,283,124,305,304,297,325,197,216,91,300,321,142,419,361,377,259,303,353,311,224,259,292,292,115,322,281,44,315,aaron holiday

# Transformation 2: Create a new column for whole team name from abbreviation

In [66]:
#Step 1: get the abbreviated team names used in the dataset
unique_values = player_stats['TEAM_ABBREVIATION'].unique()
unique_values

array(['TOR', 'MIL', 'WAS', 'DEN', 'HOU', 'IND', 'OKC', 'CHI', 'PHI',
       'BOS', 'MIA', 'LAL', 'DET', 'LAC', 'POR', 'ORL', 'DAL', 'MIN',
       'NYK', 'NOP', 'SAS', 'PHX', 'GSW', 'MEM', 'CHA', 'UTA', 'BKN',
       'ATL', 'CLE', 'SAC'], dtype=object)

In [67]:
#Step 2: created a dictionary for the full team names, ignoring nan
team_full_name = {
    'ATL': 'Atlanta Hawks',
    'BOS': 'Boston Celtics',
    'BKN': 'Brooklyn Nets',
    'CHA': 'Charlotte Hornets',
    'CHI': 'Chicago Bulls',
    'CLE': 'Cleveland Cavaliers',
    'DAL': 'Dallas Mavericks',
    'DEN': 'Denver Nuggets',
    'DET': 'Detroit Pistons',
    'GSW': 'Golden State Warriors',
    'HOU': 'Houston Rockets',
    'IND': 'Indiana Pacers',
    'LAC': 'Los Angeles Clippers',
    'LAL': 'Los Angeles Lakers',
    'MEM': 'Memphis Grizzlies',
    'MIA': 'Miami Heat',
    'MIL': 'Milwaukee Bucks',
    'MIN': 'Minnesota Timberwolves',
    'NOP': 'New Orleans Pelicans',
    'NYK': 'New York Knicks',
    'OKC': 'Oklahoma City Thunder',
    'ORL': 'Orlando Magic',
    'PHI': 'Philadelphia 76ers',
    'PHX': 'Phoenix Suns',
    'POR': 'Portland Trail Blazers',
    'SAC': 'Sacramento Kings',
    'SAS': 'San Antonio Spurs',
    'TOR': 'Toronto Raptors',
    'UTA': 'Utah Jazz',
    'WAS': 'Washington Wizards'
}

#Step 3: create new column with team full names from dictionary
player_stats['Whole Team Name'] = player_stats['TEAM_ABBREVIATION'].map(team_full_name)
player_stats.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,Player_clean,Whole Team Name
0,1630639,A.J. Lawson,A.J.,1610612761,TOR,24.0,26,14,12,0.538,486.410000,80,190,0.421,33,101,0.327,43,63,0.683,20,66,86,31,15,13,6,12,44,38,236,-17,427.7,2,0,424.0,424,364,146,239,379,352,340,388,282,281,319,281,267,419,364,359,368,397,414,397,383,241,200,327,337,299,375,159,44,364,aj lawson,Toronto Raptors
1,1631260,AJ Green,AJ,1610612749,MIL,25.0,73,44,29,0.603,1659.141667,182,424,0.429,155,363,0.427,22,27,0.815,18,156,174,108,40,37,7,3,157,50,541,227,1003.8,0,0,1066.0,86,62,362,164,152,231,220,353,58,77,37,364,372,180,381,227,261,215,286,235,370,99,498,290,214,62,247,281,44,225,aj green,Milwaukee Bucks
2,1642358,AJ Johnson,AJ,1610612764,WAS,20.0,29,8,21,0.276,638.386667,82,213,0.385,24,90,0.267,32,37,0.865,8,51,59,76,35,12,3,18,50,27,220,-152,414.8,0,0,409.0,412,445,253,473,338,348,325,472,319,294,425,312,335,87,455,386,410,281,313,406,441,312,217,369,347,495,379,281,44,372,aj johnson,Washington Wizards
3,203932,Aaron Gordon,Aaron,1610612743,DEN,29.0,51,33,18,0.647,1446.716667,264,497,0.531,75,172,0.436,145,179,0.810,80,167,247,164,73,23,14,37,82,137,748,301,1328.4,3,0,1308.0,275,166,211,101,185,150,182,79,191,222,24,89,93,196,104,206,173,128,180,329,265,451,301,107,139,41,183,134,44,181,aaron gordon,Denver Nuggets
4,1628988,Aaron Holiday,Aaron,1610612745,HOU,28.0,62,39,23,0.629,792.246667,117,268,0.437,72,181,0.398,34,41,0.829,13,65,78,83,37,19,11,11,64,49,340,88,611.1,0,0,633.0,192,100,283,124,305,304,297,325,197,216,91,300,321,142,419,361,377,259,303,353,311,224,259,292,292,115,322,281,44,315,aaron holiday,Houston Rockets

In [68]:
#validate the changes in the new col
unique_values2 = player_stats['Whole Team Name'].unique()
unique_values2

array(['Toronto Raptors', 'Milwaukee Bucks', 'Washington Wizards',
       'Denver Nuggets', 'Houston Rockets', 'Indiana Pacers',
       'Oklahoma City Thunder', 'Chicago Bulls', 'Philadelphia 76ers',
       'Boston Celtics', 'Miami Heat', 'Los Angeles Lakers',
       'Detroit Pistons', 'Los Angeles Clippers',
       'Portland Trail Blazers', 'Orlando Magic', 'Dallas Mavericks',
       'Minnesota Timberwolves', 'New York Knicks',
       'New Orleans Pelicans', 'San Antonio Spurs', 'Phoenix Suns',
       'Golden State Warriors', 'Memphis Grizzlies', 'Charlotte Hornets',
       'Utah Jazz', 'Brooklyn Nets', 'Atlanta Hawks',
       'Cleveland Cavaliers', 'Sacramento Kings'], dtype=object)

# Transformation 3: Update percentage column entries from decimal format to more readable percentage format

In [69]:
player_stats['W_PCT'] = player_stats['W_PCT'] * 100
player_stats['FG_PCT'] = player_stats['FG_PCT'] * 100
player_stats['FG3_PCT'] = player_stats['FG3_PCT'] * 100
player_stats['FT_PCT'] = player_stats['FT_PCT'] * 100

player_stats.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,Player_clean,Whole Team Name
0,1630639,A.J. Lawson,A.J.,1610612761,TOR,24.0,26,14,12,53.8,486.410000,80,190,42.1,33,101,32.7,43,63,68.3,20,66,86,31,15,13,6,12,44,38,236,-17,427.7,2,0,424.0,424,364,146,239,379,352,340,388,282,281,319,281,267,419,364,359,368,397,414,397,383,241,200,327,337,299,375,159,44,364,aj lawson,Toronto Raptors
1,1631260,AJ Green,AJ,1610612749,MIL,25.0,73,44,29,60.3,1659.141667,182,424,42.9,155,363,42.7,22,27,81.5,18,156,174,108,40,37,7,3,157,50,541,227,1003.8,0,0,1066.0,86,62,362,164,152,231,220,353,58,77,37,364,372,180,381,227,261,215,286,235,370,99,498,290,214,62,247,281,44,225,aj green,Milwaukee Bucks
2,1642358,AJ Johnson,AJ,1610612764,WAS,20.0,29,8,21,27.6,638.386667,82,213,38.5,24,90,26.7,32,37,86.5,8,51,59,76,35,12,3,18,50,27,220,-152,414.8,0,0,409.0,412,445,253,473,338,348,325,472,319,294,425,312,335,87,455,386,410,281,313,406,441,312,217,369,347,495,379,281,44,372,aj johnson,Washington Wizards
3,203932,Aaron Gordon,Aaron,1610612743,DEN,29.0,51,33,18,64.7,1446.716667,264,497,53.1,75,172,43.6,145,179,81.0,80,167,247,164,73,23,14,37,82,137,748,301,1328.4,3,0,1308.0,275,166,211,101,185,150,182,79,191,222,24,89,93,196,104,206,173,128,180,329,265,451,301,107,139,41,183,134,44,181,aaron gordon,Denver Nuggets
4,1628988,Aaron Holiday,Aaron,1610612745,HOU,28.0,62,39,23,62.9,792.246667,117,268,43.7,72,181,39.8,34,41,82.9,13,65,78,83,37,19,11,11,64,49,340,88,611.1,0,0,633.0,192,100,283,124,305,304,297,325,197,216,91,300,321,142,419,361,377,259,303,353,311,224,259,292,292,115,322,281,44,315,aaron holiday,Houston Rockets

# Transformation 4: Change 'MIN' column name

## I kept reading 'MIN' as minimum, so updating column heading to be more understandable for Minutes Played.

In [70]:
player_stats = player_stats.rename(columns = {'MIN': 'Mins_Played'})
player_stats.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,Mins_Played,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,Player_clean,Whole Team Name
0,1630639,A.J. Lawson,A.J.,1610612761,TOR,24.0,26,14,12,53.8,486.410000,80,190,42.1,33,101,32.7,43,63,68.3,20,66,86,31,15,13,6,12,44,38,236,-17,427.7,2,0,424.0,424,364,146,239,379,352,340,388,282,281,319,281,267,419,364,359,368,397,414,397,383,241,200,327,337,299,375,159,44,364,aj lawson,Toronto Raptors
1,1631260,AJ Green,AJ,1610612749,MIL,25.0,73,44,29,60.3,1659.141667,182,424,42.9,155,363,42.7,22,27,81.5,18,156,174,108,40,37,7,3,157,50,541,227,1003.8,0,0,1066.0,86,62,362,164,152,231,220,353,58,77,37,364,372,180,381,227,261,215,286,235,370,99,498,290,214,62,247,281,44,225,aj green,Milwaukee Bucks
2,1642358,AJ Johnson,AJ,1610612764,WAS,20.0,29,8,21,27.6,638.386667,82,213,38.5,24,90,26.7,32,37,86.5,8,51,59,76,35,12,3,18,50,27,220,-152,414.8,0,0,409.0,412,445,253,473,338,348,325,472,319,294,425,312,335,87,455,386,410,281,313,406,441,312,217,369,347,495,379,281,44,372,aj johnson,Washington Wizards
3,203932,Aaron Gordon,Aaron,1610612743,DEN,29.0,51,33,18,64.7,1446.716667,264,497,53.1,75,172,43.6,145,179,81.0,80,167,247,164,73,23,14,37,82,137,748,301,1328.4,3,0,1308.0,275,166,211,101,185,150,182,79,191,222,24,89,93,196,104,206,173,128,180,329,265,451,301,107,139,41,183,134,44,181,aaron gordon,Denver Nuggets
4,1628988,Aaron Holiday,Aaron,1610612745,HOU,28.0,62,39,23,62.9,792.246667,117,268,43.7,72,181,39.8,34,41,82.9,13,65,78,83,37,19,11,11,64,49,340,88,611.1,0,0,633.0,192,100,283,124,305,304,297,325,197,216,91,300,321,142,419,361,377,259,303,353,311,224,259,292,292,115,322,281,44,315,aaron holiday,Houston Rockets

# Transformation 5: Remove decimals from Mins_Played

## Since minutes played currently has six decimal places, rounding up to make more readable.

In [71]:
player_stats['Mins_Played'] = np.ceil(player_stats['Mins_Played'])
player_stats.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,Mins_Played,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,Player_clean,Whole Team Name
0,1630639,A.J. Lawson,A.J.,1610612761,TOR,24.0,26,14,12,53.8,487.0,80,190,42.1,33,101,32.7,43,63,68.3,20,66,86,31,15,13,6,12,44,38,236,-17,427.7,2,0,424.0,424,364,146,239,379,352,340,388,282,281,319,281,267,419,364,359,368,397,414,397,383,241,200,327,337,299,375,159,44,364,aj lawson,Toronto Raptors
1,1631260,AJ Green,AJ,1610612749,MIL,25.0,73,44,29,60.3,1660.0,182,424,42.9,155,363,42.7,22,27,81.5,18,156,174,108,40,37,7,3,157,50,541,227,1003.8,0,0,1066.0,86,62,362,164,152,231,220,353,58,77,37,364,372,180,381,227,261,215,286,235,370,99,498,290,214,62,247,281,44,225,aj green,Milwaukee Bucks
2,1642358,AJ Johnson,AJ,1610612764,WAS,20.0,29,8,21,27.6,639.0,82,213,38.5,24,90,26.7,32,37,86.5,8,51,59,76,35,12,3,18,50,27,220,-152,414.8,0,0,409.0,412,445,253,473,338,348,325,472,319,294,425,312,335,87,455,386,410,281,313,406,441,312,217,369,347,495,379,281,44,372,aj johnson,Washington Wizards
3,203932,Aaron Gordon,Aaron,1610612743,DEN,29.0,51,33,18,64.7,1447.0,264,497,53.1,75,172,43.6,145,179,81.0,80,167,247,164,73,23,14,37,82,137,748,301,1328.4,3,0,1308.0,275,166,211,101,185,150,182,79,191,222,24,89,93,196,104,206,173,128,180,329,265,451,301,107,139,41,183,134,44,181,aaron gordon,Denver Nuggets
4,1628988,Aaron Holiday,Aaron,1610612745,HOU,28.0,62,39,23,62.9,793.0,117,268,43.7,72,181,39.8,34,41,82.9,13,65,78,83,37,19,11,11,64,49,340,88,611.1,0,0,633.0,192,100,283,124,305,304,297,325,197,216,91,300,321,142,419,361,377,259,303,353,311,224,259,292,292,115,322,281,44,315,aaron holiday,Houston Rockets

# Transformation 6: Check for any duplicate rows

In [72]:
#Step 1: determine the amount of duplicate rows
duplicates = player_stats[player_stats.duplicated(keep=False)]
duplicates

Empty DataFrame
Columns: [PLAYER_ID, PLAYER_NAME, NICKNAME, TEAM_ID, TEAM_ABBREVIATION, AGE, GP, W, L, W_PCT, Mins_Played, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, PTS, PLUS_MINUS, NBA_FANTASY_PTS, DD2, TD3, WNBA_FANTASY_PTS, GP_RANK, W_RANK, L_RANK, W_PCT_RANK, MIN_RANK, FGM_RANK, FGA_RANK, FG_PCT_RANK, FG3M_RANK, FG3A_RANK, FG3_PCT_RANK, FTM_RANK, FTA_RANK, FT_PCT_RANK, OREB_RANK, DREB_RANK, REB_RANK, AST_RANK, TOV_RANK, STL_RANK, BLK_RANK, BLKA_RANK, PF_RANK, PFD_RANK, PTS_RANK, PLUS_MINUS_RANK, NBA_FANTASY_PTS_RANK, DD2_RANK, TD3_RANK, WNBA_FANTASY_PTS_RANK, Player_clean, Whole Team Name]
Index: []

Since no duplicates found, no further action needed.

# Final Table

In [73]:
player_stats

     PLAYER_ID               PLAYER_NAME         NICKNAME     TEAM_ID  \
0      1630639               A.J. Lawson             A.J.  1610612761
1      1631260                  AJ Green               AJ  1610612749
2      1642358                AJ Johnson               AJ  1610612764
3       203932              Aaron Gordon            Aaron  1610612743
4      1628988             Aaron Holiday            Aaron  1610612745
5      1630174             Aaron Nesmith            Aaron  1610612754
6      1630598             Aaron Wiggins            Aaron  1610612760
7      1641745              Adam Flagler             Adam  1610612760
8      1641766              Adama Sanogo            Adama  1610612741
9      1641737                 Adem Bona             Adem  1610612755
10     1642349             Ajay Mitchell             Ajay  1610612760
11      201143                Al Horford               Al  1610612738
12      202692                Alec Burks             Alec  1610612748
13     1627936               Alex Caruso             Alex  1610612760
14     1642505                Alex Ducas             Alex  1610612760
15      203458                  Alex Len             Alex  1610612747
16     1642024                Alex Reese             Alex  1610612755
17     1642259                 Alex Sarr             Alex  1610612764
18     1631214          Alondes Williams          Alondes  1610612765
19     1630578            Alperen Sengun          Alperen  1610612745
20     1641708             Amen Thompson             Amen  1610612745
21     1629599               Amir Coffey             Amir  1610612746
22      203083            Andre Drummond            Andre  1610612755
23     1641748         Andre Jackson Jr.            Andre  1610612749
24     1629614           Andrew Nembhard           Andrew  1610612754
25      203952            Andrew Wiggins           Andrew  1610612748
26     1629014           Anfernee Simons         Anfernee  1610612757
27     1641710             Anthony Black          Anthony  1610612753
28      203076             Anthony Davis          Anthony  1610612742
29     1630162           Anthony Edwards          Anthony  1610612750
30     1630264              Anthony Gill          Anthony  1610612764
31     1641817              Anton Watson            Anton  1610612752
32     1641810            Antonio Reeves          Antonio  1610612740
33     1630574            Ariel Hukporti            Ariel  1610612752
34     1642422              Armel Traore            Armel  1610612747
35     1641709            Ausar Thompson            Ausar  1610612765
36     1630559             Austin Reaves           Austin  1610612747
37     1630245               Ayo Dosunmu              Ayo  1610612741
38     1628389               Bam Adebayo              Bam  1610612748
39     1631248         Baylor Scheierman           Baylor  1610612738
40     1641767              Ben Sheppard              Ben  1610612754
41     1627732               Ben Simmons              Ben  1610612746
42     1631097        Bennedict Mathurin        Bennedict  1610612754
43     1641731           Bilal Coulibaly            Bilal  1610612764
44      202687           Bismack Biyombo          Bismack  1610612759
45     1631104              Blake Wesley            Blake  1610612759
46     1626171              Bobby Portis            Bobby  1610612749
47     1641752             Bobi Klintman             Bobi  1610612765
48      203992         Bogdan Bogdanović           Bogdan  1610612746
49     1629626                   Bol Bol              Bol  1610612756
50     1630538              Bones Hyland            Bones  1610612750
51      203078              Bradley Beal          Bradley  1610612756
52     1642382           Branden Carlson          Branden  1610612760
53     1641764        Brandin Podziemski          Brandin  1610612744
54     1630527            Brandon Boston          Brandon  1610612740
55     1629634            Brandon Clarke          Brandon  1610612763
56     1627742            Brandon Ingram          Brandon  1610612761
57     1641706            Brandon Miller          Brandon  1610612766
58     1630314          Brandon Williams          Brandon  1610612742
59     1630296               Braxton Key          Braxton  1610612744
60     1641729          Brice Sensabaugh            Brice  1610612762
61     1642355              Bronny James           Bronny  1610612747
62      201572               Brook Lopez            Brook  1610612749
63     1628971               Bruce Brown            Bruce  1610612740
64     1628981            Bruno Fernando            Bruno  1610612761
65     1631121            Bryce McGowens            Bryce  1610612757
66     1642267            Bub Carrington              Bub  1610612764
67     1627741               Buddy Hield            Buddy  1610612744
68      203468               CJ McCollum               CJ  1610612740
69     1630595           Cade Cunningham             Cade  1610612765
70     1631216             Caleb Houstan            Caleb  1610612753
71     1628997              Caleb Martin            Caleb  1610612742
72     1642353              Cam Christie              Cam  1610612746
73     1629629               Cam Reddish              Cam  1610612747
74     1642285               Cam Spencer              Cam  1610612763
75     1630560                Cam Thomas              Cam  1610612751
76     1641715              Cam Whitmore              Cam  1610612745
77     1629661           Cameron Johnson          Cameron  1610612751
78     1626166             Cameron Payne          Cameron  1610612752
79     1627747              Caris LeVert            Caris  1610612737
80     1641717             Cason Wallace            Cason  1610612760
81     1629646            Charles Bassey          Charles  1610612759
82     1631096             Chet Holmgren             Chet  1610612760
83     1628449             Chris Boucher            Chris  1610612761
84     1630537              Chris Duarte            Chris  1610612741
85     1641753          Chris Livingston            Chris  1610612749
86      101108                Chris Paul            Chris  1610612759
87     1631128           Christian Braun        Christian  1610612743
88     1631132          Christian Koloko        Christian  1610612747
89     1629643               Chuma Okeke            Chuma  1610612739
90      203991              Clint Capela            Clint  1610612737
91     1629632                Coby White             Coby  1610612741
92     1628998               Cody Martin             Cody  1610612756
93     1642262             Cody Williams             Cody  1610612762
94     1641732               Colby Jones            Colby  1610612764
95     1630175              Cole Anthony             Cole  1610612763
96     1631306               Cole Swider             Cole  1610612761
97     1630658           Colin Castleton            Colin  1610612761
98     1631221          Collin Gillespie           Collin  1610612756
99     1629012             Collin Sexton           Collin  1610612762
100    1630557             Corey Kispert            Corey  1610612764
101     202709               Cory Joseph             Cory  1610612753
102    1641854          Craig Porter Jr.            Craig  1610612739
103    1642385                Cui Yongxi              Cui  1610612751
104    1626156          D'Angelo Russell         D'Angelo  1610612751
105    1630618               D.J. Carton             D.J.  1610612761
106    1629610           DaQuan Jeffries           DaQuan  1610612766
107    1631342           Daeqwon Plowden          Daeqwon  1610612737
108    1630227               Daishen Nix          Daishen  1610612750
109    1630625             Dalano Banton           Dalano  1610612757
110    1631207               Dalen Terry            Dalen  1610612741
111    1642261             Dalton Knecht           Dalton  1610612747
112     203081            Damian Lillard           Damian  1610612749
113    1641878              Damion Baugh           Damion  1610612766
114    1627814                Damion Lee           Damion  1610612756
115    1629655            Daniel Gafford           Daniel  1610612742
116    1628464              Daniel Theis           Daniel  1610612740
117    1642450            Daniss Jenkins           Daniss  1610612765
118     203957                Danté Exum            Danté  1610612742
119     203967               Dario Šarić            Dario  1610612743
120    1641727           Dariq Whitehead            Dariq  1610612751
121    1629636            Darius Garland           Darius  1610612739
122    1630561            David Duke Jr.            David  1610612759
123    1631223               David Roddy            David  1610612745
124    1630558           Davion Mitchell           Davion  1610612748
125    1630549            Day'Ron Sharpe          Day'Ron  1610612751
126    1628368              De'Aaron Fox         De'Aaron  1610612759
127    1629631           De'Andre Hunter         De'Andre  1610612739
128    1629001         De'Anthony Melton       De'Anthony  1610612751
129     201599            DeAndre Jordan          DeAndre  1610612743
130     201942             DeMar DeRozan            DeMar  1610612758
131    1629731                 Dean Wade             Dean  1610612739
132    1629028             Deandre Ayton          Deandre  1610612757
133    1627749           Dejounte Murray         Dejounte  1610612740
134    1626153              Delon Wright            Delon  1610612752
135    1630166               Deni Avdija             Deni  1610612757
136     203471           Dennis Schröder           Dennis  1610612765
137    1641726          Dereck Lively II           Dereck  1610612742
138    1627884         Derrick Jones Jr.          Derrick  1610612746
139    1628401             Derrick White          Derrick  1610612738
140    1630217              Desmond Bane          Desmond  1610612753
141    1626164              Devin Booker            Devin  1610612756
142    1642269              Devin Carter            Devin  1610612758
143    1630170             Devin Vassell            Devin  1610612759
144    1628415             Dillon Brooks           Dillon  1610612745
145    1641794              Dillon Jones           Dillon  1610612760
146    1627734          Domantas Sabonis         Domantas  1610612758
147    1631230           Dominick Barlow         Dominick  1610612737
148    1642270           Donovan Clingan          Donovan  1610612757
149    1628378          Donovan Mitchell          Donovan  1610612739
150    1628978          Donte DiVincenzo            Donte  1610612750
151    1627827       Dorian Finney-Smith           Dorian  1610612747
152     203926            Doug McDermott             Doug  1610612758
153     203110            Draymond Green         Draymond  1610612744
154    1629234              Drew Eubanks             Drew  1610612746
155    1641809             Drew Peterson             Drew  1610612738
156    1631166                Drew Timme             Drew  1610612751
157    1630696                 Dru Smith              Dru  1610612748
158    1629130           Duncan Robinson           Duncan  1610612748
159    1641871                Duop Reath             Duop  1610612757
160     203939             Dwight Powell           Dwight  1610612742
161    1630700             Dyson Daniels            Dyson  1610612737
162    1630604              E.J. Liddell             E.J.  1610612741
163     203901             Elfrid Payton           Elfrid  1610612740
164    1641989           Elijah Harkless           Elijah  1610612762
165    1641801            Emanuel Miller          Emanuel  1610612741
166    1641734               Emoni Bates            Emoni  1610612739
167    1642402           Enrique Freeman          Enrique  1610612754
168     201569               Eric Gordon             Eric  1610612755
169    1630596               Evan Mobley             Evan  1610612739
170    1630532              Franz Wagner            Franz  1610612753
171    1627832             Fred VanVleet             Fred  1610612745
172    1641713                GG Jackson               GG  1610612763
173    1629216              Gabe Vincent             Gabe  1610612747
174     202066            Garrett Temple          Garrett  1610612761
175    1629726          Garrison Mathews         Garrison  1610612737
176     203914               Gary Harris             Gary  1610612753
177    1627780            Gary Payton II             Gary  1610612744
178    1629018            Gary Trent Jr.             Gary  1610612749
179    1627777             Georges Niang          Georges  1610612737
180     203507     Giannis Antetokounmpo          Giannis  1610612749
181    1629048              Goga Bitadze             Goga  1610612753
182    1641711               Gradey Dick           Gradey  1610612761
183    1629684            Grant Williams            Grant  1610612766
184    1628960             Grayson Allen          Grayson  1610612756
185    1627824        Guerschon Yabusele        Guerschon  1610612755
186    1630611                Gui Santos              Gui  1610612744
187     203084           Harrison Barnes         Harrison  1610612759
188    1631127           Harrison Ingram         Harrison  1610612759
189    1629312         Haywood Highsmith          Haywood  1610612748
190    1630529             Herbert Jones          Herbert  1610612740
191    1641816              Hunter Tyson           Hunter  1610612743
192    1630193         Immanuel Quickley         Immanuel  1610612761
193    1642403               Isaac Jones            Isaac  1610612758
194    1630171               Isaac Okoro            Isaac  1610612739
195    1642268            Isaiah Collier           Isaiah  1610612762
196    1642384           Isaiah Crawford           Isaiah  1610612758
197    1628392        Isaiah Hartenstein           Isaiah  1610612760
198    1630543            Isaiah Jackson           Isaiah  1610612754
199    1630198                Isaiah Joe           Isaiah  1610612760
200    1630600             Isaiah Mobley           Isaiah  1610612755
201    1641815            Isaiah Stevens           Isaiah  1610612748
202    1630191            Isaiah Stewart           Isaiah  1610612765
203    1631209               Isaiah Wong           Isaiah  1610612766
204    1627826               Ivica Zubac            Ivica  1610612746
205    1631120                JD Davison               JD  1610612738
206    1630550                   JT Thor               JT  1610612764
207    1629630                 Ja Morant               Ja  1610612763
208    1642266            Ja'Kobe Walter          Ja'Kobe  1610612761
209    1631095          Jabari Smith Jr.           Jabari  1610612745
210    1631133             Jabari Walker           Jabari  1610612757
211    1629098              Jack McVeigh             Jack  1610612745
212    1642050              Jackson Rowe          Jackson  1610612744
213    1631210              Jacob Toppin            Jacob  1610612737
214    1630702               Jaden Hardy            Jaden  1610612742
215    1631093                Jaden Ivey            Jaden  1610612765
216    1630183           Jaden McDaniels            Jaden  1610612750
217    1630531            Jaden Springer            Jaden  1610612762
218     203109               Jae Crowder              Jae  1610612758
219    1630256             Jae'Sean Tate         Jae'Sean  1610612745
220    1626143             Jahlil Okafor           Jahlil  1610612754
221    1642443              Jahmir Young           Jahmir  1610612741
222    1631170          Jaime Jaquez Jr.            Jaime  1610612748
223    1631222              Jake LaRavia             Jake  1610612758
224    1627751              Jakob Poeltl            Jakob  1610612761
225    1641779             Jalen Bridges            Jalen  1610612756
226    1628973             Jalen Brunson            Jalen  1610612752
227    1631105               Jalen Duren            Jalen  1610612765
228    1630224               Jalen Green            Jalen  1610612745
229    1641720       Jalen Hood-Schifino            Jalen  1610612755
230    1630552             Jalen Johnson            Jalen  1610612737
231    1629667           Jalen McDaniels            Jalen  1610612764
232    1629618             Jalen Pickett            Jalen  1610612743
233    1630188               Jalen Smith            Jalen  1610612741
234    1630591               Jalen Suggs            Jalen  1610612753
235    1631114            Jalen Williams            Jalen  1610612760
236    1630592              Jalen Wilson            Jalen  1610612751
237    1631288                Jamal Cain            Jamal  1610612740
238    1627750              Jamal Murray            Jamal  1610612743
239    1642347               Jamal Shead            Jamal  1610612761
240    1631123            Jamaree Bouyea          Jamaree  1610612749
241     201935              James Harden            James  1610612746
242     201949             James Johnson            James  1610612754
243    1630164             James Wiseman            James  1610612754
244    1642419            Jamison Battle          Jamison  1610612761
245    1641716             Jarace Walker           Jarace  1610612754
246    1630215              Jared Butler            Jared  1610612755
247    1642272              Jared McCain            Jared  1610612755
248    1631197              Jared Rhoden            Jared  1610612761
249    1628991         Jaren Jackson Jr.            Jaren  1610612763
250    1629020         Jarred Vanderbilt           Jarred  1610612747
251    1628386             Jarrett Allen          Jarrett  1610612739
252    1629750             Javonte Green          Javonte  1610612739
253    1629637              Jaxson Hayes           Jaxson  1610612747
254    1630643                  Jay Huff              Jay  1610612763
255    1627759              Jaylen Brown           Jaylen  1610612738
256    1641740              Jaylen Clark           Jaylen  1610612750
257    1641798             Jaylen Martin           Jaylen  1610612764
258    1629669             Jaylen Nowell           Jaylen  1610612740
259    1631301               Jaylen Sims           Jaylen  1610612766
260    1642377              Jaylen Wells           Jaylen  1610612763
261    1631119           Jaylin Williams           Jaylin  1610612760
262    1642281              Jaylon Tyson           Jaylon  1610612739
263    1628369              Jayson Tatum           Jayson  1610612738
264    1641789            Jazian Gortman           Jazian  1610612742
265    1630288           Jeff Dowtin Jr.             Jeff  1610612755
266     201145                Jeff Green             Jeff  1610612745
267     203924              Jerami Grant           Jerami  1610612757
268    1630526    Jeremiah Robinson-Earl         Jeremiah  1610612740
269    1631110             Jeremy Sochan           Jeremy  1610612759
270    1630579              Jericho Sims          Jericho  1610612749
271    1642399             Jesse Edwards            Jesse  1610612750
272    1641724               Jett Howard             Jett  1610612753
273    1628975              Jevon Carter            Jevon  1610612741
274     202710          Jimmy Butler III            Jimmy  1610612744
275    1629111              Jock Landale             Jock  1610612745
276     204060                Joe Ingles              Joe  1610612750
277     203954               Joel Embiid             Joel  1610612755
278    1628381              John Collins             John  1610612762
279    1629723              John Konchar             John  1610612763
280    1631098              Johnny Davis           Johnny  1610612764
281    1642277             Johnny Furphy           Johnny  1610612754
282    1630548             Johnny Juzang           Johnny  1610612762
283     202685         Jonas Valančiūnas            Jonas  1610612758

In [74]:
#view full row from Final Table
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

player_stats.iloc[1]

PLAYER_ID                        1631260
PLAYER_NAME                     AJ Green
NICKNAME                              AJ
TEAM_ID                       1610612749
TEAM_ABBREVIATION                    MIL
AGE                                 25.0
GP                                    73
W                                     44
L                                     29
W_PCT                               60.3
Mins_Played                       1660.0
FGM                                  182
FGA                                  424
FG_PCT                              42.9
FG3M                                 155
FG3A                                 363
FG3_PCT                             42.7
FTM                                   22
FTA                                   27
FT_PCT                              81.5
OREB                                  18
DREB                                 156
REB                                  174
AST                                  108
TOV                                   40
STL                                   37
BLK                                    7
BLKA                                   3
PF                                   157
PFD                                   50
PTS                                  541
PLUS_MINUS                           227
NBA_FANTASY_PTS                   1003.8
DD2                                    0
TD3                                    0
WNBA_FANTASY_PTS                  1066.0
GP_RANK                               86
W_RANK                                62
L_RANK                               362
W_PCT_RANK                           164
MIN_RANK                             152
FGM_RANK                             231
FGA_RANK                             220
FG_PCT_RANK                          353
FG3M_RANK                             58
FG3A_RANK                             77
FG3_PCT_RANK                          37
FTM_RANK                             364
FTA_RANK                             372
FT_PCT_RANK                          180
OREB_RANK                            381
DREB_RANK                            227
REB_RANK                             261
AST_RANK                             215
TOV_RANK                             286
STL_RANK                             235
BLK_RANK                             370
BLKA_RANK                             99
PF_RANK                              498
PFD_RANK                             290
PTS_RANK                             214
PLUS_MINUS_RANK                       62
NBA_FANTASY_PTS_RANK                 247
DD2_RANK                             281
TD3_RANK                              44
WNBA_FANTASY_PTS_RANK                225
Player_clean                    aj green
Whole Team Name          Milwaukee Bucks
Name: 1, dtype: object

# Paragraph of the ethical implications of data wrangling specific to the datasource and the steps completed 

The transformations to the api data included: standardizing player names, team names, and percentage entries.  In addition, changed a column header name and rounded up its entries.  As for legal or regulatory risk, the use of this data does not seem to violate the NBA Terms of Use.  There should not be any risks from the minor transformations done to the dataset.  The primary assumption for this dataset is that the nba_api library is properly pulling correct data from the NBA for the 2024-25 season.  The nba_api library is an unofficial Python client that sources the data from the NBA's official statistics website (stats.nba.com) and other official NBA endpoints.  There is no reason to believe the data was acquired in an unethical way.  Mitigation of any data concerns can be checked against other similar sources for accuracy.